---
name: Supply-chain compliance for Github artefacts (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      artifact-ref:
        description: Github artifact reference to add supply chain metadata to
        required: true
        type: string
      name:
        description: String used to name the metadata artifact that will be generated
        required: true
        type: string

jobs:
  # SBOM can be used to filter images based on software requirements (avoid some dependencies,
  # allow only GPL compatible licenses, etc.)
  sbom:
    name: SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        id: download-oci
        with:
          name: ${{ inputs.artifact-ref }}

      - name: Extract OCI-Archive for Trivy
        run: "skopeo copy oci-archive:${{ inputs.artifact-ref }} oci:${{ github.workspace }}/trivy-${{ github.run_id }}"

      - uses: aquasecurity/trivy-action@7c2007bcb556501da015201bcba5aa14069b74e2 # 0.23.0
        with:
          input: trivy-${{ github.run_id }}
          format: cyclonedx
          output: sbom.cyclonedx.json

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: sbom-cyclonedx.${{ inputs.name }}.json
          path: sbom.cyclonedx.json

  # Vulnerability report can be used to filter images based on software vulnerabilities (avoid some CVEs,
  # allow only low severity, etc.)
  vulnerability:
    name: Vulnerability
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        id: download-oci
        with:
          name: ${{ inputs.artifact-ref }}

      - name: Extract OCI-Archive for Trivy
        run: skopeo copy oci-archive:${{ inputs.artifact-ref }} oci:${{ github.workspace }}/trivy-${{ github.run_id }}

      - uses: aquasecurity/trivy-action@7c2007bcb556501da015201bcba5aa14069b74e2 # 0.23.0
        with:
          input: trivy-${{ github.run_id }}
          format: cosign-vuln
          output: vulnerabilities.cosign-vuln.json
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: cosign-vuln.${{ inputs.name }}.json
          path: vulnerabilities.cosign-vuln.json

      # Upload SARIF report for GitHub CodeQL at the same time
      - uses: aquasecurity/trivy-action@7c2007bcb556501da015201bcba5aa14069b74e2 # 0.23.0
        with:
          input: trivy-${{ github.run_id }}
          format: sarif
          output: vulnerabilities.sarif
      - uses: github/codeql-action/upload-sarif@9a866ed4524fc3422c3af1e446dab8efa3503411 # codeql-bundle-20230418
        with:
          category: trivy-container
          sarif_file: vulnerabilities.sarif
