---
name: List changed images (container)
on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      pattern:
        description: Glob pattern to match image files
        required: false
        type: string
        default: |
          charts/**/Dockerfile
    outputs:
      containerfiles:
        description: List of changed Containerfiles
        value: ${{ jobs.list-changed.outputs.containerfiles }}

jobs:
  list-changed:
    name: List changed images
    outputs:
      containerfiles: ${{ steps.format-output.outputs.json }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 10

      - uses: tj-actions/changed-files@cc733854b1f224978ef800d29e4709d5ee2883e4 # v44.5.5
        id: changed-images
        with:
          files: ${{ inputs.pattern }}
          json: true
      - id: format-output
        run: echo "json=${{ steps.changed-images.outputs.all_changed_files }}" >> "${GITHUB_OUTPUT}"
