---
name: Synchronize labels
on:  # yamllint disable-line rule:truthy
  repository_dispatch:
    types: [sync-labels]
  schedule:
    - cron: 0 3 * * 0,3
  workflow_dispatch:

jobs:
  sync-labels:
    name: Synchronize org. '${{ github.repository_owner }}' labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: beluga-cloud/.github
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
